---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ruoyi
  labels:
    app: redis-service-labels
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
  selector:
    app: redis-pod-labels
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: ruoyi
  labels:
    app: redis-deployment-labels
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-pod-labels
  template:
    metadata:
      labels:
        app: redis-pod-labels
    spec:
      tolerations:
      - operator: Exists
      nodeSelector:     ## 配置该容器调度到指定节点，前提是将指定节点打好标签  ##
        ruoyi: "true"
      #tolerations:
      #- key: "env"
      #  operator: "Equal"
      #  value: "guance"
      #  effect: "NoSchedule"
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      # 修改容器内核参数方式一，初始化容器，改somaxconn参数。
      initContainers:
        - name: system-init
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - "sh"
            - "-c"
            - "echo 1024 > /proc/sys/net/core/somaxconn && echo never > /sys/kernel/mm/transparent_hugepage/enabled"
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
          - name: sys
            mountPath: /sys
      containers:
        - name: redis
          image: redis:5.0.8
          command:
            - "sh"
            - "-c"
            - "redis-server /usr/local/etc/redis/redis.conf"
          ports:
            - containerPort: 6379
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 300
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: redis-config
        - name: sys
          hostPath:
            path: /sys
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-config
  namespace: ruoyi
  labels:
    app: redis-configmap-labels
data:
  redis.conf: |-
    dir /data
    port 6379
    bind 0.0.0.0
    appendonly yes
    protected-mode no
    pidfile /data/redis-6379.pid
